### ISSUE TITLE
Error for __declspec

### ISSUE THREAD

**Issue by trelau** [robotpy/cxxheaderparser#12]
When parsing:

```cpp
class CDM_MetaData : public Standard_Transient
{

public:

friend class CDM_Reference;
friend
  //! associates database  information to  a document which
  //! has been stored.  The name of the  document is now the
  //! name which has beenused to store the data.
  __declspec( dllexport ) void CDM_Document::SetMetaData (const opencascade::handle<CDM_MetaData>& aMetaData);
friend
  __declspec( dllexport ) void CDM_Application::SetDocumentVersion (const opencascade::handle<CDM_Document>& aDocument, const opencascade::handle<CDM_MetaData>& aMetaData) const;

};
```

I am parsing the OpenCASCADE headers, by the way. That is where all the errors are coming from.

**Comment by virtuald** [comment]
Hm, then you'll probably run into #5 at some point? What's the use case here, do you want to have access to the __declspec or is it fine if it's just discarded?

**Comment by trelau** [comment]
Good point, in this case I can likely discard it when preprocessing. It may only be useful it if gives a hint that a function may not be in the library that the Python bindings will ultimately be linked to, so it'd be a hint to skip it in the downstream tools.

If I can ignore it, then I can handle that upstream with pcpp, so perhaps not a priority.

**Comment by trelau** [comment]
Use is to generate Python bindings for OpenCASCADE. I have this project already https://github.com/trelau/pyOCCT, but it currently uses clang for the binding generator, which is giving me headaches. This project seemed like a nice alternative, so thought  I'd try it out.

**Comment by trelau** [comment]
Note that this doesn't show up for every __declspec, only a handful of instances out of thousands of occurrences.

**Comment by virtuald** [comment]
Ah, so you're doing essentially the same thing that I'm doing at https://github.com/robotpy/robotpy-build/ then (also using pybind11). Maybe it would make sense to collaborate on the autobinding stuff? I know it has the name RobotPy in it, but it's intended to be general.

I have robotpy-build about 25% of the way converted over to cxxheaderparser, but I'm not going to be able to get to finishing that work until later on next week because the FIRST Robotics Kickoff is this weekend.

**Comment by virtuald** [comment]
In particular it's worth pointing out the hooks/templates that I'm using to autogenerate the pybind11 bindings are a terrible terrible mess in part because it was built on CppHeaderParser, so I'm rebuilding them from scratch.

**Comment by trelau** [comment]
Cool, I wasn't aware of that. I'll check it out. I've thought about how to make a general tool for Python bindings, but so far I've had to handle so many edge cases in pyOCCT I haven't thought it'd be a fruitful endeavor.

**Comment by virtuald** [comment]
I've also got a lot of edge cases, they're just likely different. :) The documentation still needs work, but the tests should show some of the weird edge cases (templates, mostly) that we do handle.

It's great that you're finding all of the edge cases for cxxheaderparser, I imagine I'll run into at least some of them once I get robotpy-build ported over and start building the libraries I'm wrapping. Thanks.

If you have questions/thoughts I'm happy to discuss in real time at https://gitter.im/robotpy/robotpy-wpilib

**Comment by trelau** [comment]
Cool. I'll experiment with it for the python bindings. This file [here](https://github.com/trelau/pyOCCT/blob/master/binder/config.txt) sort of gives you a sense of some of the stuff I have to work around. Most of it is relatively simple:

- Excluding classes
- Excluding typedefs
- Excluding methods (based on name or signature)
- Overwriting method calls entirely

The hardest part is the circular dependencies that show up between all the various modules that I end up making (over 300 if I remember correctly). I have to manually track them down and add import guards and such. That was the pain point that recently made me search for alternatives and landed on pcpp, this project, and now robotpy-build.

**Comment by virtuald** [comment]
* Excluding classes: yep, theres a YAML file that you can put the name of the class and mark it as ignored
  * https://github.com/robotpy/robotpy-build/blob/main/tests/cpp/gen/ft/ignore.yml
* Excluding typedefs: I don't actually think I wrap them right now since they're not useful in python? 
* Excluding methods (based on name or signature): same thing, the YAML file
* Overwriting method calls entirely: yep, there's a 'cpp_code' available for overriding (https://github.com/robotpy/robotpy-build/blob/e79a4aec0ac2de46ed9a834dca28bfa5e6ed8d30/tests/cpp/gen/ft/ignore.yml#L17)
* Customer holder: I don't remember if I support that, but it'd be an easy enough thing to add
* Adding extra headers in certain files: yep

The circular dependencies thing (in a single module) is handled by two-phase initialization of types. For module-to-module depndencies, I think right now you have to have a DAG -- but there are ways to work around that depending on how hairy it gets. Usually I've just combined the modules together into an _impl module and then had separate python packages import from the _impl module.

**Comment by trelau** [comment]
Cool. For typedefs, the code is using something like:

```cpp
typedef SomeTemplate<Arg, Arg> SomeNewTypeIWantInPython;
```

So, I guess I should add to the list wrapping templated items.  [Here](https://github.com/trelau/pyOCCT/blob/master/inc/bind_Define_HArray1.hxx) is an example where the binding generator would write a function from a template, then that can be called in the python bindings.

**Comment by virtuald** [comment]
Got it, that makes sense. Currently the libraries I'm using don't use typedefs like that, so in the YAML you have to manually instantiate each template:

class:
* Header: https://github.com/robotpy/robotpy-build/blob/main/tests/cpp/rpytest/ft/include/templates/basic.h
* YAML: https://github.com/robotpy/robotpy-build/blob/main/tests/cpp/gen/ft/tbasic.yml

Note the section of 'templates' -- you need to tell the generator which instantiations you want.

Function templates (once again, need to tell the generator which instantiations you want)
* fn: https://github.com/robotpy/robotpy-build/blob/main/tests/cpp/rpytest/ft/include/templates/fn.h
* yml: https://github.com/robotpy/robotpy-build/blob/main/tests/cpp/gen/ft/tfn.yml


I do like the idea of being able to retrieve the template instantiations from typedef parameters though, I don't think it would be difficult to add. Would have to be after the cxxheaderparser migration though.

Additionally, once I upgrade to cxxheaderparser I don't believe the template param names will need to be manually specified.
